import './structure.css'
export function crearEstructuraPpal() {
  let appInfo = document.querySelector('#app');
  appInfo.innerHTML = "";
  const navGames = document.createElement("nav");
  appInfo.append(navGames);
  const titleNavDiv = document.createElement("div");
  titleNavDiv.id = "titleNavDiv";
  navGames.append(titleNavDiv);
  const titleNavBefore = document.createElement("h1");
  titleNavDiv.append(titleNavBefore);
  titleNavBefore.innerText = "🎲♦️🎲 ";
  titleNavBefore.id = "titleNavBefore";
  titleNavBefore.className = "titleNavAll";
  const titleNav = document.createElement("h1");
  titleNavDiv.append(titleNav);
  titleNav.innerText = " Games  Hub ";
  titleNav.id = "titleNav";
  titleNav.className = "titleNavAll";
  const titleNavAfter = document.createElement("h1");
  titleNavDiv.append(titleNavAfter);
  titleNavAfter.innerText = "🎲♦️🎲";
  titleNavAfter.id = "titleNavAfter";
  titleNavAfter.className = "titleNavAll";
  const pNav = document.createElement("p");
  navGames.append(pNav);
  pNav.innerText = "¡¡Aquí están tus juegos favoritos, elige a cual quieres jugar!!";
  pNav.id = "pInitialNav";
  const divNav = document.createElement("div");
  divNav.id = "divNav";
  navGames.append(divNav);
  let gamesInfo = ["tresEnRaya", "laOca", "memory"];
  gamesInfo.forEach(e => {
    const divGameDiv = document.createElement("div");
    const divGame = document.createElement("button");
    const divGameImg = document.createElement("img");
    divGameDiv.className = "divNavGames";
    divGame.id = `${e}Select`;
    divGameImg.id = `${e}SelectImg`;
    divGame.className = `buttonNavGames`;
    divGameImg.className = `imgNavGames`;
    divNav.append(divGameDiv);
    divGameDiv.append(divGame);
    divGameDiv.append(divGameImg);
    divGame.textContent = `${e}`
    const game = document.createElement("section");
    game.id = e;
    appInfo.appendChild(game);
    const volverAlNav = document.createElement("button");
    volverAlNav.innerHTML = "Volver a la pantalla principal y jugar a otro juego";
    volverAlNav.id = `${e}ReturnToNav`;
    volverAlNav.className = `returnToNav`;
    game.append(volverAlNav);
    const title = document.createElement("h2");
    title.className = `gameTitle`;
    title.id = `${e}Title`;
    game.appendChild(title);
    const ultimoGanador = document.createElement("h4");
    ultimoGanador.id = `ultimoGanador${e}`;
    console.log(`estoy en ${e} `);
    console.log(ultimoGanador);
    ultimoGanador.className = "ultimosGanadores";
    const gameContainer = document.createElement("div");
    gameContainer.id = `${e}Container`;
    const gameTable = document.createElement("div");
    gameTable.id = `${e}Table`;
    const gamePlayers = document.createElement("div");
    gamePlayers.id = `${e}Players`;
    game.appendChild(gameContainer);
    gameContainer.appendChild(gameTable);
    gameContainer.appendChild(gamePlayers);
    title.insertAdjacentElement("afterend", ultimoGanador);
  });
  // Los 3 juegos en la pantalla principal
  const tresEnRayaSelectGame = document.getElementById("tresEnRayaSelect");
  tresEnRayaSelectGame.innerText = "JUGAR AL TRES EN RAYA";
  const tresEnRayaSelectGameImg = document.getElementById("tresEnRayaSelectImg");
  tresEnRayaSelectGameImg.src = `assets/TresEnRayaFoto.png`;
  const laOcaSelectGame = document.getElementById("laOcaSelect");
  laOcaSelectGame.innerText = "JUGAR A LA OCA";
  const laOcaSelectGameImg = document.getElementById("laOcaSelectImg");
  laOcaSelectGameImg.src = `assets/OcaFoto.png`;
  const memorySelectGame = document.getElementById("memorySelect");
  memorySelectGame.innerText = "JUGAR AL MEMORY";
  const memorySelectGameImg = document.getElementById("memorySelectImg");
  memorySelectGameImg.src = `assets/MemoryFoto.png`;
  const tresEnRayaTitleGame = document.getElementById("tresEnRayaTitle");
  tresEnRayaTitleGame.innerText = "JUGAR AL TRES EN RAYA";
  const laOcaTitle = document.getElementById("laOcaTitle");
  laOcaTitle.innerText = "JUGAR A LA OCA";
  const memoryTitle = document.getElementById("memoryTitle");
  memoryTitle.innerText = "JUGAR AL MEMORY";
};